version: "3.8"

services:
  db:
    image: mysql:8
    container_name: ecommerce_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 58915281
      MYSQL_DATABASE: ecommerce_db
    ports:
      - "3306:3306"
    volumes:
      - ./backend/sql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecommerce_backend
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 58915281
      DB_NAME: ecommerce_db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm start

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ecommerce_frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm start

volumes:
  mysql_data:
